credentials:
  discord:
    client: 692484003428564994
    secret: n28mEv-SqBExsqThSNZEDVEgQ3pKRGrH
    token: NjkyNDg0MDAzNDI4NTY0OTk0.XnvOPw.GKaEFbORz8l4_PhOfCQT8-aP3fc

sources:
  discord:
    server: mariocesar_xyz
    channel: general

  youtube:
    chatid: qptP9oepvQA